"""A generated, committed file must not carry an absolute path of any shape.

`tests/test_no_private_paths.py` scans for a home directory, which is the shape
that is actually private. It cannot catch this one on the machine that writes it:
this checkout lives at `D:\\trialsieve`, so a traceback stored into
`results/contamination.json` looked clean here and wrote a home directory into a
tracked file seven times as soon as the repository was cloned under one. The leak
was found by cloning into a temporary directory and running `python run.py
reproduce`, which is the thing a judge does and the thing the author does not.

So the rule here is stricter and machine-independent: a file this repository
generates and commits carries no absolute path at all. That rejects
`D:\\trialsieve` too, which is not private, because it is the carrier. It is also
the property that lets two machines produce the same bytes.

The scan is over generated artifacts only. Prose is exempt because a document may
legitimately quote a command, and `docs/agent-traces/` is exempt because a shell
transcript is a record of a shell and is redacted by `scripts/agent_traces.py`
under its own test.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
from trialsieve import redact  # noqa: E402

#: Everything below is written by a script rather than by a person. Each entry is
#: a glob, and each is here because something in it is regenerated by
#: `python run.py reproduce`.
GENERATED = [
    "results/*.json",
    "results/published/*.json",
    "results/RESULTS.md",
    "docs/COST.md",
    "docs/CONTAMINATION.md",
    "docs/COUNTEREXAMPLE.md",
    "docs/GATE.md",
    "docs/SCORECARD.md",
    "docs/sample_worklist.md",
    "docs/sample_worklist.json",
    "docs/sample_worklist.csv",
    "runs/*/trajectories/index.md",
    "film/src/data.json",
    "film/src/timings.json",
    "film/receipts/*.json",
]


def _files(pattern: str) -> list[Path]:
    return sorted(ROOT.glob(pattern))


def test_the_scan_covers_something() -> None:
    """A glob that matches nothing passes silently, which is the wrong kind of green."""
    found = sum(len(_files(p)) for p in GENERATED)
    assert found >= 10, (
        f"only {found} generated files matched; the globs in GENERATED have "
        "drifted from the tree and this test is no longer checking anything"
    )


#: Parametrised over the patterns, not over the files they match. Over the files,
#: the number of tests is a function of which generated artifacts happen to exist,
#: so a clean clone collects a different count from the tree that wrote it and
#: `test_reproduce_guide_quotes_the_real_test_count` fails on a machine nobody
#: can see. It did, by exactly one.
@pytest.mark.parametrize("pattern", GENERATED)
def test_generated_files_carry_no_absolute_path(pattern: str) -> None:
    found = _files(pattern)
    assert found, f"{pattern!r} matches nothing; it names a file that has moved or gone"
    hits = [
        f"{path.relative_to(ROOT).as_posix()}:{i}: {line.strip()[:120]}"
        for path in found
        for i, line in enumerate(
            path.read_text(encoding="utf-8", errors="replace").splitlines(), 1)
        if redact.has_absolute_path(line)
    ]
    assert not hits, (
        f"{len(hits)} generated line(s) record the machine that generated them. "
        f"First: {hits[0]}\n"
        "Pass the value through `trialsieve.redact.paths(text, ROOT)` where it is "
        "written, rather than editing the committed file."
    )


def test_the_scan_can_fail() -> None:
    """A positive control, in every shape the writers actually produce.

    The shapes are assembled rather than written out. Spelled literally, this
    file becomes a tracked file containing a home directory, and
    `tests/test_no_private_paths.py` fails on it: a scanner flagging another
    scanner's test data is a real failure with a useless cause. That happened,
    and only in a clean clone, because the file was untracked in the tree it was
    written in and `git ls-files` never offered it.
    """
    bs = chr(92)
    user = "some" + "one"
    planted = [
        'File "C:' + bs + "Users" + bs + user + bs + 'a.py", line 1',
        "File " + bs + '"C:' + bs * 2 + "Users" + bs * 2 + user + bs * 2 + "a.py",
        "/" + "home" + "/" + user + "/repo/a.py",
        "/" + "Users" + "/" + user + "/repo/a.py",
        "D:/trialsieve/scripts/a.py",
    ]
    for line in planted:
        assert redact.has_absolute_path(line), f"the scan misses {line!r}"
    assert not redact.has_absolute_path("scripts/contamination.py, line 295")
    assert not redact.has_absolute_path("runs/tierA/cells/cells_TS.jsonl")


if __name__ == "__main__":
    raise SystemExit(pytest.main([__file__, "-q"]))
