"""The cost table at the top of the README, read back out of `docs/COST.md`.

The README opens with the comparison a person paying for this reads first. Those
figures live in `docs/COST.md`, which is generated by `scripts/costs.py` from the
recorded call counts at published rates, so the README's copy is a second copy.

This repository has already been bitten twice by exactly that. Entry 40 was a
SNOMED code that existed in one file and nowhere else. The changelog's own size
was typed into three documents and was wrong in all three while the one derived
figure stayed right. A number that appears in two places disagrees with itself
eventually, and the fix is not to be careful, it is to check the copy against the
original.

So this reads both. The four money figures, the crossover point and the panel
size all have to match what `docs/COST.md` says, and the test fails loudly rather
than skipping if the README stops carrying the table at all.
"""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
README = ROOT / "README.md"
COST = ROOT / "docs" / "COST.md"


def _crossover_row() -> tuple[str, str]:
    """The full-panel row: compiled-path cost, then per-cell cost."""
    for line in COST.read_text(encoding="utf-8").splitlines():
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) == 3 and cells[0].isdigit() and int(cells[0]) > 100:
            return cells[1], cells[2]
    raise AssertionError("docs/COST.md has no full-panel row in its crossover table")


def _rescreen_row() -> tuple[str, str]:
    """The `385 again next month` row, which is where the argument actually is."""
    for line in COST.read_text(encoding="utf-8").splitlines():
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) == 3 and "again next month" in cells[0]:
            return cells[1], cells[2]
    raise AssertionError("docs/COST.md no longer carries a rescreen row")


def _readme_table() -> str:
    text = README.read_text(encoding="utf-8")
    start = text.find("| 385 patients, 40 criteria,")
    assert start != -1, (
        "README.md no longer opens with the cost table, so this file is checking "
        "nothing. Either restore it or delete this test rather than leaving a "
        "green check over a claim that moved.")
    return text[start:start + 1200]


def test_the_readme_quotes_the_costs_in_the_cost_table() -> None:
    compiled, per_cell = _crossover_row()
    table = _readme_table()
    assert per_cell in table, (
        f"docs/COST.md says a screening pass costs {per_cell} asking per cell and "
        f"the README's table does not contain that figure")
    assert compiled in table, (
        f"docs/COST.md says the compiled path costs {compiled} and the README's "
        f"table does not contain that figure")


def test_the_readme_quotes_the_rescreen_row() -> None:
    compiled, per_cell = _rescreen_row()
    table = _readme_table()
    assert compiled in table and per_cell in table, (
        f"the rescreen row of docs/COST.md reads {compiled} against {per_cell}, "
        f"and the README's table does not carry both. That row is the whole "
        f"argument: one side of the comparison is flat and the other is not.")


def test_the_readme_quotes_the_crossover_point() -> None:
    m = re.search(r"cross at \*\*([\d.]+) patients\*\*", COST.read_text(encoding="utf-8"))
    assert m, "docs/COST.md no longer states where the two costs cross"
    assert f"cross at {m.group(1)} patients" in README.read_text(encoding="utf-8"), (
        f"docs/COST.md puts the crossover at {m.group(1)} patients and the README "
        f"does not say the same thing")


def test_the_header_names_the_set_the_cost_rows_are_counted_over() -> None:
    """The header has to be the panel the money is counted over, not another one.

    This test already caught the table quoting a cost measured over 15,400 cells
    beside a worklist measured over 1,155, with one header over both. That is the
    defect entry 41 is about, so the header names the cost rows' set and the
    worklist row carries its own scope inline.
    """
    import json  # noqa: PLC0415
    res = json.loads((ROOT / "results" / "results.json").read_text(encoding="utf-8"))
    cells = res["groups"]["k0_seed7"]["cell_scores"]["TS"]["n_cells"]
    panel = json.loads(
        (ROOT / "data" / "vendor" / "panel_code_counts.json").read_text(encoding="utf-8"))
    header = _readme_table().splitlines()[0]
    assert f"{cells:,}" in header, (
        f"the cost rows are counted over {cells:,} cells and the header {header!r} "
        f"does not say so")
    assert str(panel["n_patients"]) in header, (
        f"the panel has {panel['n_patients']} patients and the header does not "
        f"say so")


def test_the_worklist_row_carries_its_own_denominator() -> None:
    """A row counted over a different set has to say which set, in the row."""
    import json  # noqa: PLC0415
    wl = json.loads(
        (ROOT / "docs" / "sample_worklist.json").read_text(encoding="utf-8"))
    table = _readme_table()
    row = next((l for l in table.splitlines() if "coordinator is handed" in l), "")
    assert row, "the README table no longer has the coordinator row"
    for figure in (f"{wl['n_cells']:,}", str(wl["n_review"]),
                   str(len(wl["criteria_used"]))):
        assert figure in row, (
            f"the coordinator row does not carry {figure!r}, which is one of the "
            f"numbers that says which set it is counted over. Without all three "
            f"it reads as though it shares the header's denominator, and it does "
            f"not.")
