"""Count, per code, how much of the screened panel actually carries it.

    python scripts/build_panel_counts.py

Writes `data/vendor/panel_code_counts.json`. That file already existed and had no
generator anywhere in this repository, which is how it came to be wrong: it listed
674 codes when the panel carries 677, and one of the three it omitted is `8331-1`,
oral temperature, on 214 of the 385 panel patients.

That omission was not cosmetic. `explain.empty_closed_world_codes` read a missing
entry as a count of zero and warned a reviewer that a code most of the panel
carries appears on no chart. The warning exists to catch a closed-world query over
a code nobody has, which is the failure that silently clears a whole panel. Firing
it on a common code trains a reviewer to ignore it, which disables the check for
the case it was built for.

Two counts per code and they answer different questions:

  `rows`      resources carrying the code. A patient with nine HbA1c results
              contributes nine.
  `patients`  distinct patients carrying it at least once. This is the one the
              closed-world warning uses, because the question there is how many
              charts could have been the evidence.

The catalog counts the whole source corpus and this counts the panel that was
screened. They are different populations on purpose and conflating them is the
mistake this file exists to make visible.
"""
from __future__ import annotations

import argparse
import collections
import gzip
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

DOMAINS = ("conditions", "medications", "observations", "procedures")


def count(panel: Path) -> tuple[dict[str, dict[str, int]], int]:
    rows: collections.Counter = collections.Counter()
    patients: collections.Counter = collections.Counter()
    n = 0
    with gzip.open(panel, "rt", encoding="utf-8") as fh:
        for line in fh:
            if not line.strip():
                continue
            p = json.loads(line)
            n += 1
            seen: set[str] = set()
            for dom in DOMAINS:
                for item in p.get(dom) or []:
                    for coding in item.get("codes") or []:
                        if len(coding) >= 2 and coding[1]:
                            code = str(coding[1])
                            rows[code] += 1
                            seen.add(code)
            for code in seen:
                patients[code] += 1
    out = {c: {"rows": rows[c], "patients": patients[c]} for c in sorted(rows)}
    return out, n


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--panel", default="data/vendor/panel.jsonl.gz")
    ap.add_argument("--out", default="data/vendor/panel_code_counts.json")
    ap.add_argument("--check", action="store_true",
                    help="do not write; exit 1 if the committed file disagrees")
    a = ap.parse_args()

    panel = ROOT / a.panel
    if not panel.exists():
        print(f"no panel at {panel}", file=sys.stderr)
        return 2
    counts, n = count(panel)

    blob = {
        "panel": a.panel,
        "n_patients": n,
        "note": ("Rows and distinct patients per code in the panel actually "
                 "screened. The terminology catalog counts the whole source "
                 "corpus, which is a larger and different set. Generated by "
                 "scripts/build_panel_counts.py; a code absent from `counts` is "
                 "absent from the panel, and callers must not read a missing "
                 "entry as a count of zero."),
        "counts": counts,
    }
    text = json.dumps(blob, indent=1) + "\n"
    dest = ROOT / a.out

    if a.check:
        if not dest.exists():
            print(f"NOT COMPARED: {dest} does not exist", file=sys.stderr)
            return 1
        old = json.loads(dest.read_text(encoding="utf-8"))
        oc = old.get("counts", {})
        missing = sorted(set(counts) - set(oc))
        extra = sorted(set(oc) - set(counts))
        wrong = sorted(c for c in counts if c in oc and oc[c] != counts[c])
        if missing or extra or wrong:
            print(f"the committed counts disagree with the panel: "
                  f"{len(missing)} missing, {len(extra)} not in the panel, "
                  f"{len(wrong)} with a different count", file=sys.stderr)
            for c in missing[:10]:
                print(f"  missing {c}: {counts[c]['patients']} patients",
                      file=sys.stderr)
            for c in wrong[:10]:
                print(f"  {c}: committed {oc[c]}, panel {counts[c]}", file=sys.stderr)
            return 1
        print(f"the committed counts match the panel: {len(counts)} codes, "
              f"{n} patients")
        return 0

    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {dest}: {len(counts)} codes over {n} patients")
    top = sorted(counts.items(), key=lambda kv: -kv[1]["patients"])[:5]
    for c, v in top:
        print(f"  {c:12s} {v['patients']:4d} patients, {v['rows']:5d} rows")
    return 0


if __name__ == "__main__":
    sys.exit(main())
