"""What the prompt change did, on the split that was declared for changing prompts.

    python scripts/compare_dev.py runs/dev-before runs/dev-after

The development split has no gold labels and never will, which is deliberate:
`docs/DEV_SPLIT.md` fixed that before the first prompt edit so that iteration
could not be fitted to an answer key. So this cannot report accuracy. What it can
report is what the two runs did with the same thirty criteria, and where they
disagreed.

**The trap this report is built around.** More criteria compiling is not better.
A prompt that produces a confident predicate for "willing and able to give
informed consent" has got worse while its compile rate went up, and a summary that
showed only the rate would call that an improvement. There is no gold label here
to catch it.

So the rate is reported, and then every criterion that changed direction is
printed in full with its text and its predicate, and the reader adjudicates. The
list is short by construction, which is what makes it readable. A change that
flipped twenty criteria would produce twenty rows to argue with, and that is the
correct amount of friction for a change that large.

**The three refusal reasons are kept apart.** A criterion refused because the
site's vocabulary has no code for a concept is a different event from one refused
because the plan step judged it uncheckable from a record. Adding them would let
a vocabulary fix and a plan regression cancel out to no visible change.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))


def outcome(rec: dict) -> str:
    if rec.get("compile_error"):
        return "error"
    if rec.get("compilable"):
        return "compiled"
    if rec.get("blocked_at") == "grounding":
        return "refused: vocabulary"
    return "refused: plan"


def load(run: Path, seed: int = 7) -> tuple[dict, dict]:
    p = run / "compiled" / f"criteria_seed{seed}.json"
    if not p.exists():
        print(f"{p} does not exist. That arm has not finished.", file=sys.stderr)
        raise SystemExit(2)
    blob = json.loads(p.read_text(encoding="utf-8"))
    return blob, {c["criterion_id"]: c for c in blob["criteria"]}


def one_line(rec: dict) -> str:
    if not rec.get("compilable"):
        return str(rec.get("reason_not_compilable", ""))[:200]
    try:
        from trialsieve import explain
        return explain.expr(rec["expr"], 0).replace("\n", " ")[:260]
    except Exception:
        return json.dumps(rec.get("expr"))[:260]


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__, file=sys.stderr)
        return 2
    b_run, a_run = Path(sys.argv[1]), Path(sys.argv[2])
    b_blob, before = load(b_run)
    a_blob, after = load(a_run)

    shared = sorted(set(before) & set(after))
    if not shared:
        print("the two runs share no criteria", file=sys.stderr)
        return 2

    counts: dict[tuple[str, str], list[str]] = {}
    for cid in shared:
        counts.setdefault((outcome(before[cid]), outcome(after[cid])), []).append(cid)

    kinds = ["compiled", "refused: vocabulary", "refused: plan", "error"]
    b_tot = {k: sum(1 for c in shared if outcome(before[c]) == k) for k in kinds}
    a_tot = {k: sum(1 for c in shared if outcome(after[c]) == k) for k in kinds}

    L = ["# The prompt change, on the development split", "",
         "Generated by `python scripts/compare_dev.py`. Output, not illustration.", "",
         f"{len(shared)} criteria, drawn by seed from the five development trials before",
         "the first prompt edit. No gold labels here, by design: see `docs/DEV_SPLIT.md`.",
         "So this is not an accuracy report and does not claim to be one.", "",
         f"| outcome | before (`{b_blob.get('model', '?')}`) | after | change |",
         "|---|---|---|---|"]
    for k in kinds:
        d = a_tot[k] - b_tot[k]
        L.append(f"| {k} | {b_tot[k]} | {a_tot[k]} | {d:+d} |")
    L += ["", "## Why the rate alone would be the wrong thing to read", "",
          "More criteria compiling is not better. A prompt that produces a confident",
          "predicate for a criterion about willingness to consent has got worse while its",
          "compile rate went up, and there is no gold label on this split to catch it.",
          "So every criterion that changed direction is below, with its text and what the",
          "predicate says, for a reader to disagree with.", ""]

    moved = [(k, v) for k, v in sorted(counts.items()) if k[0] != k[1]]
    stayed = sum(len(v) for k, v in counts.items() if k[0] == k[1])
    L.append(f"{stayed} of {len(shared)} criteria did not change direction. "
             f"{len(shared) - stayed} did.")
    L.append("")

    for (b_out, a_out), cids in moved:
        good = b_out.startswith("refused") and a_out == "compiled"
        L.append(f"### {b_out} to {a_out}  ({len(cids)})")
        L.append("")
        L.append("A criterion that now compiles has to be one that should. Read the "
                 "predicate." if good else
                 "A criterion that stopped compiling is a regression unless the refusal "
                 "is right. Read the reason.")
        L.append("")
        for cid in cids:
            L.append(f"**`{cid}`**")
            L.append("")
            L.append(f"> {before[cid].get('source_text', '')}")
            L.append("")
            L.append(f"- before: {one_line(before[cid])}")
            L.append(f"- after: {one_line(after[cid])}")
            L.append("")

    for name, blob in (("before", b_blob), ("after", a_blob)):
        s = blob.get("stats", {})
        u = blob.get("usage", {})
        L.append(f"`{name}`: {json.dumps(s)}")
        L.append("")
        L.append(f"`{name}` usage: {json.dumps(u)}, wall {blob.get('wall_s')} s")
        L.append("")

    out = ROOT / "docs" / "DEV_COMPARISON.md"
    out.write_text("\n".join(L), encoding="utf-8", newline="\n")
    js = ROOT / "results" / "dev_comparison.json"
    js.parent.mkdir(parents=True, exist_ok=True)
    js.write_text(json.dumps(
        {"n_shared": len(shared), "before": b_tot, "after": a_tot,
         "before_model": b_blob.get("model"), "after_model": a_blob.get("model"),
         "transitions": {f"{k[0]} -> {k[1]}": v for k, v in sorted(counts.items())},
         "unchanged": stayed}, indent=1) + "\n", encoding="utf-8", newline="\n")
    print("\n".join(L[:24]))
    print(f"\nwrote {out} and {js}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
