"""The human checkpoint, demonstrated by running into it.

    python scripts/gate_demo.py --run runs/tierA

Writes `docs/GATE.md`. Every block in it is captured output including the exit
codes, because "the system refuses without sign-off" is the kind of claim that is
easy to write and easy to have quietly stopped being true.

Three states, and the middle one is the one worth showing:

1. **Unsigned.** `scripts/worklist.py` exits 3 and names what to run. No document
   is produced.
2. **Unsigned, overridden.** The `--allow-unsigned` flag produces the document and
   stamps NOT FOR USE across it. The flag exists so the gate can be demonstrated,
   and using it is visible in the artifact rather than only in a shell history.
3. **Signed.** Only if a signature exists in this checkout. Signing is a human
   action and this script does not perform it; if nobody has signed, this section
   says so rather than filling in.

The reason there is no `--approve-all` anywhere in this repository is the same
reason this file exists. A gate you can clear without reading is a gate that
reports approval nobody gave.
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))


def run(args: list[str]) -> tuple[int, str]:
    p = subprocess.run([sys.executable, *args], cwd=ROOT, capture_output=True,
                       text=True, encoding="utf-8", errors="replace")
    return p.returncode, ((p.stdout or "") + (p.stderr or "")).strip()


#: Small counts read as words in prose and as digits in a table. These are the
#: only ones this document can produce.
_WORDS = {1: "one", 2: "two", 3: "three", 4: "four", 5: "five", 6: "six"}


def _count(n: int) -> str:
    return _WORDS.get(n, str(n))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--run", default="runs/tierA")
    ap.add_argument("--trial", default="")
    ap.add_argument("--out", default="docs/GATE.md")
    a = ap.parse_args()

    from trialsieve.signoff import load

    run_dir = Path(a.run)
    # Somewhere the gate can be told to write that nothing publishes. It has
    # twice been a directory that later stopped existing, and a demo of a
    # refusal that fails because its scratch path is gone reads exactly like
    # the refusal, so this one is a directory the repository always has.
    tmp = ROOT / "docs" / "_gate_demo.md"

    # The sample ships at the published operating point. Rendered with every
    # compiled criterion it ruled out 385 of 385 and handed a coordinator an
    # empty list, which is a measurement configuration rather than a product.
    base = ["scripts/worklist.py", "--run", a.run, "--operating-point", "0"]
    if a.trial:
        base += ["--trial", a.trial]

    # Relative paths, and the same argument list is printed as was run. An
    # absolute --out made the captured line read "wrote D:\...", which both
    # published a local directory layout and did not match the command shown
    # above it, so the transcript disagreed with itself.
    refuse_cmd = base + ["--out", tmp.relative_to(ROOT).as_posix()]
    allow_cmd = base + ["--allow-unsigned", "--out", "docs/sample_worklist.md"]
    rc_refuse, out_refuse = run(refuse_cmd)
    rc_allow, out_allow = run(allow_cmd)

    signoffs = load(run_dir / "signoffs.jsonl")
    banner = ""
    sample = ROOT / "docs" / "sample_worklist.md"
    if sample.exists():
        head = sample.read_text(encoding="utf-8").splitlines()
        banner = next((l for l in head if "NOT FOR USE" in l or "signed by" in l), "")

    L = ["# The human checkpoint, demonstrated by running into it", "",
         "Generated by `python scripts/gate_demo.py`. Exit codes and output are captured,",
         "not transcribed.", "",
         "The only artifact in this project that could affect a person is the worklist a",
         "coordinator opens. It cannot be produced from predicates a named human has not",
         "signed. That is enforced by exit code, and the refusal is tested.", "",
         "---", "", "## 1. Unsigned", "",
         "```", "$ python " + " ".join(refuse_cmd) + "  ; echo $?",
         out_refuse[:1400], str(rc_refuse), "```", "",
         "Exit code **" + str(rc_refuse) + "**. No document was written. The message names "
         "the command that clears the gate, and clearing it means reading one predicate at "
         "a time: `scripts/signoff.py` has no bulk approval and no `--approve-all`, because "
         "a gate you can clear without reading reports approval nobody gave.", ""]
    # The refusal above counts the rejections inside the criterion set that one
    # invocation was asked to build a worklist from, and section 3 counts the run.
    # Both numbers are right and a reader who sees only the two of them has no way
    # to know that, so the difference is stated here rather than left to be
    # noticed. It is computed rather than typed: an operating point that selected
    # a different subset would otherwise leave a sentence behind describing the
    # old one.
    rejected_all = sorted(sg.criterion_id for sg in signoffs.values()
                          if sg.decision == "REJECTED")
    named_here = [cid for cid in rejected_all if cid in out_refuse]
    only_in_run = [cid for cid in rejected_all if cid not in out_refuse]
    if only_in_run and named_here:
        L += ["**" + _count(len(named_here)).capitalize() + " here, " + _count(len(rejected_all))
              + " in section 3, and both are right.** The operating point selects a "
              "subset of the compiled criteria before the gate sees them, so the "
              "refusal names the rejections inside the set this invocation was asked "
              "to build a worklist from: " + ", ".join("`" + c + "`" for c in named_here)
              + ". The run carries " + _count(len(rejected_all)) + " in total, adding "
              + ", ".join("`" + c + "`" for c in only_in_run) + ", and section 3 counts "
              "the run rather than one command's view of it. The gate refuses either "
              "way; what the operating point changes is how many rejected criteria it "
              "has to name. Read them all with `python scripts/signoff.py --run "
              + run_dir.as_posix() + " --list`.", ""]
    L += [
         "## 2. Unsigned, overridden on purpose", "",
         "```", "$ python " + " ".join(allow_cmd) + "  ; echo $?",
         out_allow[:1200], str(rc_allow), "```", ""]
    if banner:
        L += ["The document is produced and the first thing on it is this:", "",
              "> " + banner.strip(), "",
              "The override leaves a mark in the artifact rather than only in a shell",
              "history, which is the point. A reader who is handed the file can tell.", "",
              "It marks both halves. For a while it marked only this one: "
              "`sample_worklist.json`", "carried no trace of the override, so an "
              "unsigned worklist was byte-identical in shape", "to a signed one for "
              "anything downstream that reads JSON rather than prose. The", "sidecar "
              "now carries `not_for_use` and the reviewer, and "
              "`tests/test_worklist_sidecar_is_complete.py`", "checks the two against "
              "each other and against this document.", ""]

    L += ["## 3. Signed", ""]
    if signoffs:
        who = sorted({s.reviewer for s in signoffs.values()})
        roles = sorted({s.reviewer_role for s in signoffs.values()})
        by = {d: [s for s in signoffs.values() if s.decision == d]
              for d in ("APPROVED", "APPROVED_WITH_NOTE", "REJECTED")}
        counts = ", ".join(f"{len(v)} {k.lower().replace('_', ' ')}"
                           for k, v in by.items() if v)
        L += [f"{len(signoffs)} predicate(s) carry a signature in this checkout, from "
              f"{', '.join(who)} ({', '.join(roles)}): {counts}.", "",
              "The signature is over the predicate digest. Recompiling changes the digest",
              "and the signature no longer applies, which is what stops an approval from",
              "carrying over to a predicate nobody read. Each one was read on its own:",
              "`scripts/signoff.py` renders a predicate into English with the codes",
              "resolved to this site's own display names, and it has no bulk approval and",
              "no `--approve-all`.", ""]
        if by["REJECTED"] or by["APPROVED_WITH_NOTE"]:
            L += ["### What the reviewer refused", "",
                  "The half of a checkpoint worth reading. A gate that only ever records",
                  "approval is a gate nobody used.", "",
                  "| criterion | decision | the reviewer's reason |",
                  "|---|---|---|"]
            for s2 in sorted(by["REJECTED"] + by["APPROVED_WITH_NOTE"],
                             key=lambda x: x.criterion_id):
                reason = " ".join(s2.rationale.split()).replace("|", "/")
                L += [f"| `{s2.criterion_id}` | {s2.decision} | {reason} |"]
            L += ["",
                  "A rejection is not a criterion quietly dropped. `signoff.enforce()`",
                  "refuses the whole worklist until the predicate is recompiled, because a",
                  "criterion the reviewer found wrong would otherwise be applied to nobody",
                  "and the document would not say so.", ""]
    else:
        L += ["**Nothing is signed in this checkout, and that is not an oversight.**", "",
              "Signing is a human action. This script does not perform it and no automated",
              "step in this repository does either, because a signature an agent applied on",
              "a human's behalf is the exact failure the gate exists to prevent. What is",
              "shipped here is the mechanism and its refusal.", "",
              "To clear it:", "",
              "```bash",
              f"python scripts/signoff.py --run {a.run} --list",
              f'python scripts/signoff.py --run {a.run} --reviewer "Your Name" \\',
              '    --role "clinical research coordinator"',
              "```", "",
              "One predicate at a time, rendered into English with the codes resolved to",
              "the display names this site's own records use. The reviewer's role is",
              "recorded in the signature, so a signature from someone who is not a",
              "clinician says so.", ""]

    # The document and both sidecars. Only the markdown was removed, so a run
    # that got past the refusal left `_gate_demo.json` and `_gate_demo.csv` in a
    # tracked directory, where they read as shipped artifacts of a demo that is
    # supposed to produce nothing.
    for stray in (tmp, tmp.with_suffix(".json"), tmp.with_suffix(".csv")):
        if stray.exists():
            stray.unlink()
    out = Path(a.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(L), encoding="utf-8", newline="\n")
    print("\n".join(L))
    print(f"\nwrote {out}")
    if rc_refuse != 3:
        print(f"\nthe unsigned run exited {rc_refuse}, not 3. The gate is not refusing.",
              file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
