"""Every path a document points at must exist.

    python scripts/linkcheck.py

A README that links to a file nobody generated is the cheapest possible way to
look careless, and it is invisible to the author, who has the file locally or
remembers meaning to make it. It is the first thing a reader hits.

This is a script rather than a test on purpose. Several of the paths are produced
by the run itself, so a test in the gate would fail on a clean checkout before the
run that creates them, and a gate that fails when nothing is wrong gets muted.
`python run.py reproduce` calls this after the generating steps, which is the
moment the answer means something.

Four kinds of reference are checked and one is deliberately not:

* markdown links, `[text](path)`
* inline code that looks like a path, `` `docs/THING.md` `` or `` `scripts/x.py` ``
* the command in a fenced block, when its first token is a script in this tree
* the `#anchor` on a link, against the headings the target document actually has

The anchor check is the one that catches a rename. A path stays valid while the
section it pointed at is retitled, so a link that resolved yesterday lands a
reader at the top of a long document with no way to tell they were sent to the
wrong place. GitHub's own slug rules are reimplemented here rather than
approximated, duplicate headings included.

External URLs are not fetched. A link checker that hits the network fails on an
aeroplane and passes when a site is merely slow, so it measures connectivity and
reports it as correctness.
"""
from __future__ import annotations

import fnmatch
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

DOCS = ["README.md", "SUBMISSION.md", "REPRODUCE.md", "results/RESULTS.md"]
# `results/RESULTS.md` is generated by `scripts/report.py` and is the document
# a reader is sent to for every headline number. It was not on this list, so
# the one file whose links are written by a generator was the one file whose
# links nothing checked.
# The trajectory indexes are generated, but the links between them are not:
# each one points at its four siblings and at `results/RESULTS.md` by a
# relative path written in `scripts/trajectories.py`, which is the class of
# reference that rots when a run is renamed.
DOC_GLOBS = ["docs/*.md", "runs/*/trajectories/index.md"]

MD_LINK = re.compile(r"\[[^\]]*\]\(([^)\s]+)(?:\s+\"[^\"]*\")?\)")
CODE_PATH = re.compile(r"`([A-Za-z0-9_./-]+\.(?:py|md|json|jsonl|yml|gz|toml|cfg))`")
CMD = re.compile(r"^\s*python3?\s+([A-Za-z0-9_./-]+\.py)", re.M)

#: Paths that name a directory of generated output rather than one file, or that
#: are illustrative. Listed here so the exemption is visible instead of being a
#: silent hole in the pattern.
EXEMPT = {
    # Generated by the run, excluded by `.gitignore`, and named in the guide as
    # what a command writes rather than as something to open. Everything else is
    # now resolved against what git tracks, so the directories that used to be
    # listed here (`results/published/`, `runs/tierA/trajectories/`,
    # `data/vendor/`, `tests/`) resolve on their own and their exemptions are
    # gone. An exemption that outlives its reason is a hole nobody is watching.
    "runs/tierA/cells/cells_B2_b2_10p.jsonl",
    "runs/tierA/cells/cells_TS-B0-B1_k0_seed7.jsonl",
    # The sign-off ledger. The README and SUBMISSION.md point at it to say where
    # the fact lives rather than to assert the fact, and the whole point of the
    # gate is that no automated step creates this file. It is absent in an
    # unsigned checkout by design, so a link checker that failed on it would be
    # reporting the safety property as a defect. If a reviewer signs, it appears
    # and this line stops doing anything.
    "runs/tierA/signoffs.jsonl",
}


#: GitHub's heading slug: drop the markup, lowercase, drop everything that is not
#: a word character, a space or a hyphen, then join on hyphens. A second heading
#: with the same text gets `-1`, a third `-2`.
_INLINE = re.compile(r"`([^`]*)`|\*\*([^*]*)\*\*|\*([^*]*)\*|\[([^\]]*)\]\([^)]*\)")
_STRIP = re.compile(r"[^\w\- ]", re.UNICODE)
_HEADING = re.compile(r"^(#{1,6})\s+(.*?)\s*#*\s*$", re.M)
_FENCE = re.compile(r"^\s*(```|~~~)", re.M)


def slugs(text: str) -> set[str]:
    """Every fragment a link into this document is allowed to use."""
    # Headings inside a fenced block are not headings. Without this, a `#` line
    # in a shell transcript invents an anchor that does not exist on GitHub.
    lines, fenced, body = text.splitlines(), False, []
    for line in lines:
        if _FENCE.match(line):
            fenced = not fenced
            body.append("")
            continue
        body.append("" if fenced else line)
    out: set[str] = set()
    seen: dict[str, int] = {}
    for m in _HEADING.finditer(chr(10).join(body)):
        title = _INLINE.sub(lambda g: next(x for x in g.groups() if x is not None),
                            m.group(2))
        slug = _STRIP.sub("", title).strip().lower().replace(" ", "-")
        if not slug:
            continue
        n = seen.get(slug, 0)
        seen[slug] = n + 1
        out.add(slug if n == 0 else f"{slug}-{n}")
    # A hand-written HTML anchor is a real target too.
    out.update(re.findall(r'<a\s+(?:id|name)="([^"]+)"', text))
    return out


def _parents(name: str) -> set[str]:
    """Every directory a tracked path implies. Git tracks files, links point at
    directories too, and `runs/tierA/trajectories/` is a real target."""
    out, parts = set(), name.split("/")
    for i in range(1, len(parts)):
        out.add("/".join(parts[:i]))
        out.add("/".join(parts[:i]) + "/")
    return out


def targets(text: str) -> set[str]:
    out: set[str] = set()
    for m in MD_LINK.finditer(text):
        out.add(m.group(1))
    for m in CODE_PATH.finditer(text):
        out.add(m.group(1))
    for m in CMD.finditer(text):
        out.add(m.group(1))
    return out


def _shipped() -> tuple[set[str], str]:
    """What a reader receives, and how that was decided.

    Asked of git, because the working tree is not what a judge gets. Every link
    once resolved here with `Path.exists()` and reported clean across 771
    references while four of them pointed at files that were generated and never
    added, so the one gate that would have caught it was the one gate that could
    not see the difference.

    An unpacked source archive has no object database, and it also has no
    untracked files, so there the directory walk answers the same question. This
    used to pass `check=True` and raise instead, which failed `run.py reproduce`
    for a reader who downloaded the zip rather than cloning.
    """
    import subprocess
    r = subprocess.run(["git", "ls-files", "-z"], cwd=ROOT,
                       capture_output=True, text=True)
    if r.returncode == 0 and r.stdout.strip():
        return {n for n in r.stdout.split(chr(0)) if n}, "git"
    walked = {q.relative_to(ROOT).as_posix() for q in ROOT.rglob("*")
              if q.is_file() and ".git" not in q.parts}
    return walked, "this directory, which has no git"


def main() -> int:
    tracked_set, source = _shipped()
    by_name = {n.rsplit("/", 1)[-1] for n in tracked_set}
    tracked_dirs = {d for n in tracked_set
                    for d in _parents(n)} if tracked_set else set()

    # The documents, also from git. A local scratch run leaves an index this
    # repository does not ship, and checking it reports that run's links as
    # defects of this one.
    files = [ROOT / d for d in DOCS]
    for g in DOC_GLOBS:
        files.extend(ROOT / n for n in sorted(tracked_set)
                     if fnmatch.fnmatch(n, g))

    missing: list[str] = []
    checked = 0
    anchors: list[tuple[Path, str, str]] = []
    for f in files:
        if not f.exists():
            missing.append(f"{f.relative_to(ROOT).as_posix()} (the document itself)")
            continue
        text = f.read_text(encoding="utf-8")
        for t in sorted(targets(text)):
            if t.startswith("#"):
                # A link into this same document. It has no path to resolve, so
                # it used to be dropped one line before the anchor check existed
                # and every internal cross-reference in the changelog went
                # unvalidated.
                anchors.append((f, "", t[1:]))
                continue
            if t.startswith(("http://", "https://", "mailto:")):
                continue
            if t in EXEMPT:
                continue
            base, _, frag = t.partition("#")
            if frag and (base.endswith(".md") or not base):
                anchors.append((f, base, frag))
            if not base:
                continue
            checked += 1
            cands = [f.parent / base, ROOT / base]
            rels = []
            for c in cands:
                try:
                    rels.append(c.resolve().relative_to(ROOT).as_posix())
                except (ValueError, OSError):
                    pass
            if any(r in tracked_set or r in tracked_dirs for r in rels):
                continue
            # A reference with no directory in it is a filename mentioned in
            # passing, `units.py` or `environment.json`, not a link. Those resolve
            # by basename anywhere in the tree. A reference that does carry a
            # directory is a claim about where the file is, and is checked as one.
            if "/" not in base and base in by_name:
                continue
            if any(c.exists() for c in cands):
                note = ("present here, absent from git, so a clone 404s"
                        if source == "git" else "present but not readable as shipped")
                missing.append(f"{f.relative_to(ROOT).as_posix()} -> {t} ({note})")
            else:
                missing.append(f"{f.relative_to(ROOT).as_posix()} -> {t}")

    # The anchors, once the paths they hang off are known to resolve.
    bad_anchors: list[str] = []
    slug_cache: dict[Path, set[str] | None] = {}
    for f, base, frag in anchors:
        target = (f.parent / base).resolve() if base else f
        if target not in slug_cache:
            try:
                slug_cache[target] = slugs(target.read_text(encoding="utf-8"))
            except OSError:
                slug_cache[target] = None
        have = slug_cache[target]
        if have is None:
            # The path check above already reported an unresolvable target, or
            # it is exempt. Either way this is not a second finding.
            continue
        if frag.lower() not in have:
            rel = target.relative_to(ROOT).as_posix() if target.is_relative_to(ROOT) else str(target)
            bad_anchors.append(
                f"{f.relative_to(ROOT).as_posix()} -> {base}#{frag} "
                f"(no such heading in {rel})")

    print(f"checked {checked} path reference(s) and {len(anchors)} anchor(s) across "
          f"{len(files)} document(s), resolved against {source}")
    missing.extend(bad_anchors)
    if missing:
        print(f"\n{len(missing)} point at something that is not there:", file=sys.stderr)
        for m in missing:
            print(f"  {m}", file=sys.stderr)
        return 1
    print("every path a document points at exists, and every anchor "
          "names a heading that is there")
    return 0


if __name__ == "__main__":
    sys.exit(main())
