"""The one table a judge asked for, generated from the scored run.

The challenge brief suggests a three-row comparison: primary outcome, human time
per task, cost per task, with a column for the simple baseline and one for the
agent solution. It also says to propose a different rubric where that one fits
badly. Both apply here, so this writes the suggested shape and says plainly
where it was adapted and why.

Two adaptations, both stated in the output rather than only here:

1. A single "primary outcome" row would hide the trade this project is about.
   `docs/EVAL_PROTOCOL.md` registers the outcome as panel reduction at zero false
   exclusions and VOID otherwise, so the reduction is reported next to the count
   that voids it, and the harm gets its own row.
2. Human time is not a stopwatch reading. Nobody was timed. What is measured is
   the number of judgements a person is left holding, which is the quantity a
   coordinator's hours are actually spent on, and the number of distinct
   questions those judgements collapse into.

Every figure comes from `results/results.json` and `docs/sample_worklist.json`.
Nothing here is typed in by hand, and `--check` fails if the file on disk has
drifted from what the current run would produce.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "SCORECARD.md"

#: The paired group. B2 is the only baseline that costs a model call per cell, so
#: it was recorded over a seeded sample rather than the whole panel. Every arm in
#: this group is scored on those same 400 cells, which is what makes the
#: comparison fair rather than merely available.
PAIRED = "b2_10p"
FULL = "k0_seed7"


def _pct(x: float) -> str:
    return f"{x * 100:.2f}%"


def _ratio(worse: float, better: float) -> str:
    """The ratio between two silent error rates.

    Never print this on its own. `evaluation/score.py` opens by saying the unit
    of result is the ordered pair (coverage, SER), because an arm that abstains
    everywhere has a silent error rate of exactly zero and is worthless. Every
    caller here prints the two coverages in the same row.
    """
    if better <= 0:
        return "no error to divide by"
    return f"{worse / better:.0f}x lower"


def build() -> str:
    res = json.loads((ROOT / "results" / "results.json").read_text(encoding="utf-8"))
    wl_path = ROOT / "docs" / "sample_worklist.json"
    wl = json.loads(wl_path.read_text(encoding="utf-8")) if wl_path.exists() else {}

    paired = res["groups"][PAIRED]
    full = res["groups"][FULL]
    ts, b2 = paired["cell_scores"]["TS"], paired["cell_scores"]["B2"]
    tsp, b2p = paired["panel_scores"]["TS"], paired["panel_scores"]["B2"]
    n_cells = ts["n_cells"]
    n_screens = paired["n_screens"]
    # The interval and the floor, read from the same file as the point estimates.
    # Two of the four headline rows were printed as bare numbers while the file
    # they were read from carried a confidence interval for one and a noise floor
    # the other sits underneath. A table that shows the estimate and hides the
    # uncertainty beside it is the table doing the arguing.
    floor = paired.get("label_floor_poststratified") or {}
    boot = {(c["arms"], c["metric"]): c
            for c in paired.get("paired_bootstrap", [])}

    L: list[str] = []
    L += ["# The comparison table, in the shape the brief asks for", ""]
    L += [f"Generated by `python scripts/scorecard.py`. Every number is read from "
          f"`results/results.json`, and the human-time row also from "
          f"`docs/sample_worklist.json`. `python run.py reproduce` regenerates "
          f"both offline from recorded model calls.", ""]
    L += [f"The rows below are scored on **the same {n_cells} cells**: "
          f"{n_screens} screens, meaning ten patients each read against three "
          f"trials, against the criteria that compiled, judged by "
          f"both arms. B2 is the only baseline that spends a model call per cell, "
          f"so it was recorded over a seeded sample rather than the full "
          f"{full['cell_scores']['TS']['n_cells']:,}-cell panel, and every arm it "
          f"is compared against is re-scored on that sample rather than quoted "
          f"from the larger run.", ""]

    L += ["## The simple baseline", ""]
    L += ["**B2: one model call per cell.** The criterion text and a flattened "
          "patient record go to the model, which answers MEETS, FAILS or "
          "INDETERMINATE. It is the brief's first suggested baseline, one direct "
          "prompt with basic instructions, and it is the version of this task "
          "most people would build first. Two weaker arms are also carried "
          "through the report: B0 answers FAILS on every cell without reading the "
          "chart, and B1 runs the compiled predicate on the criteria age and sex "
          "alone can settle and abstains on the rest.", ""]

    L += ["## The table", ""]
    L += ["| metric | simple baseline (B2) | TrialSieve | change |",
          "|---|---|---|---|"]
    L.append(f"| **Primary outcome** as registered: panel reduction at zero false "
             f"exclusions | **VOID** ({b2p['false_exclusions']} false exclusions, "
             f"reduction {_pct(b2p['reduction'])}) | **VOID** "
             f"({tsp['false_exclusions']} false exclusions, reduction "
             f"{_pct(tsp['reduction'])}) | both void; the harm behind the void "
             f"falls from {b2p['false_exclusions']} to {tsp['false_exclusions']} |")
    # The headline this project is most often quoted on. It was printed as two
    # integers and a subtraction, with no interval anywhere in the repository,
    # while the paired bootstrap on the same cells puts a 95% interval on it that
    # includes zero. Ten to two is what happened on this run; it is not a
    # difference this evaluation can separate from chance, and the row says so.
    ff = boot.get(("TS - B2", "false_fails"))
    ff_note = ""
    if ff:
        # Built outside the f-string rather than inside its braces. A multi-line
        # conditional between `{` and `}` is PEP 701, which landed in 3.12, and
        # this repository declares `requires-python = ">=3.10"`. It parsed on the
        # machine it was written on and was a SyntaxError on the version CI runs,
        # which is a file the whole gate imports failing before any test ran.
        crosses = ("which crosses zero, so this run cannot separate it from chance"
                   if ff["crosses_zero"] else "which excludes zero")
        ff_note = (f"; paired bootstrap on the same cells puts the per-cell "
                   f"difference at {ff['observed_difference']:+.4f} "
                   f"(95% CI {ff['ci_low']:+.4f} to {ff['ci_high']:+.4f}), "
                   f"{crosses}")
    L.append(f"| Screens wrongly ruled out, of {n_screens} | "
             f"{b2p['false_exclusions']} | **{tsp['false_exclusions']}** | "
             f"{b2p['false_exclusions'] - tsp['false_exclusions']} fewer"
             f"{ff_note} |")
    # The change column used to read a bare "44x lower". `evaluation/score.py`
    # says in its opening docstring that a comparison against an arm at higher
    # coverage is not admissible, and this is exactly that comparison: TS at
    # 21.75% against B2 at 68%. Printing the ratio alone in the headline table,
    # under a module that calls it inadmissible, is the submission arguing
    # against itself. The row carries both coverages now and sends the reader to
    # the paired interval.
    ser_note = ""
    if floor.get("hard") and ts["ser"] < floor["hard"]:
        ser_note = (f" (below the {floor['hard']:.1%} label noise floor, "
                    f"so it is not distinguishable from zero here)")
    L.append(f"| Silent error rate per cell, each at the coverage beside it | "
             f"{_pct(b2['ser'])} at {_pct(b2['coverage'])} coverage | "
             f"**{_pct(ts['ser'])}**{ser_note} at {_pct(ts['coverage'])} coverage | "
             f"{_ratio(b2['ser'], ts['ser'])}, at a third of the coverage |")
    L.append(f"| Cells answered with a definite verdict | {_pct(b2['coverage'])} | "
             f"{_pct(ts['coverage'])} | lower on purpose, see below |")
    # The registered co-primary, which exists so that an arm cannot win by
    # abstaining, and which the baseline wins. Printed in the same table as the
    # row it is supposed to check, because a guard reported somewhere else is not
    # a guard.
    if "resolved_correct_per_screen" in b2 and "resolved_correct_per_screen" in ts:
        rb, rt = b2["resolved_correct_per_screen"], ts["resolved_correct_per_screen"]
        verdict = ("**the baseline wins this row**" if rb > rt
                   else "TrialSieve wins this row")
        L.append(f"| Cells resolved correctly per screen, the registered co-primary | "
                 f"{rb:.2f} | {rt:.2f} | {verdict} |")
    L.append(f"| Wrong MEETS, the verdict that enrols someone who should not be | "
             f"{b2['n_false_meets']} | **{ts['n_false_meets']}** | "
             f"{b2['n_false_meets'] - ts['n_false_meets']} fewer |")

    if wl:
        sets = wl.get("question_sets") or []
        n_q = len(wl.get("distinct_open_criteria") or [])
        # This row is the one trial the worklist was rendered for, not the 400
        # cells above, and it says so. Quietly changing denominator mid-table is
        # how a comparison stops being one.
        L.append(f"| **Human time per task**, as judgements a person is left "
                 f"holding *(one trial, {wl['n_screens']} patients, not the "
                 f"sample above, and against the {len(wl['criteria_used'])} "
                 f"criteria this operating point applies rather than the trial's "
                 f"full set)* | {wl['n_cells']:,} cell judgements, the manual "
                 f"process today | {wl['n_review']:,} screens carrying **{n_q} "
                 f"distinct open questions** | {len(sets)} thing(s) to go and "
                 f"find instead of {wl['n_cells']:,} separate readings. Each "
                 f"still returns a value per patient; what collapses is the "
                 f"search, not the answers |")

    costs = _cost_rows()
    if costs:
        L.append(costs)
    L.append("")

    L += ["**On the ratio in that row.** It is the arithmetic and it is not the "
          "result. `evaluation/score.py` states that a comparison against an arm "
          "at higher coverage is not admissible, and this is that comparison: "
          f"TrialSieve answers {_pct(ts['coverage'])} of cells and B2 answers "
          f"{_pct(b2['coverage'])}. The row that does settle it is the paired "
          "bootstrap in `results/RESULTS.md`, where `TS - B2` on `ser` is "
          "reported with an interval and against the label noise floor. The "
          "ratio is here because the brief's table has a change column, not "
          "because it is the finding.", ""]
    L += ["## Reading the coverage row honestly", ""]
    if "resolved_correct_per_screen" in b2 and "resolved_correct_per_screen" in ts:
        rb, rt = b2["resolved_correct_per_screen"], ts["resolved_correct_per_screen"]
        if rb > rt:
            L += [f"**Start with the row this project loses.** `docs/EVAL_PROTOCOL.md` "
                  f"registered `resolved_correct_per_screen` as a co-primary outcome "
                  f"before the first scored run, in its own words *so an arm cannot "
                  f"win by abstaining*. B2 resolves {rb:.2f} cells correctly per "
                  f"screen and TrialSieve resolves {rt:.2f}, so the guard registered "
                  f"against this design's central objection finds against it by "
                  f"{(rb - rt) / rt:.0%}. Abstaining is free on the silent error rate "
                  f"row above and it is not free here. Everything below is the "
                  f"argument for paying that price; the price is this row.", ""]
    L += [f"TrialSieve answers fewer cells than B2 and that is the design, not a "
          f"shortfall. B2 commits to {_pct(b2['coverage'])} of cells and is wrong "
          f"on {_pct(b2['ser'])} of all cells; TrialSieve commits to "
          f"{_pct(ts['coverage'])} and is wrong on {_pct(ts['ser'])}. A "
          f"coordinator cannot use an answer that is wrong two times in five, "
          f"because checking which two costs the same as reading the chart. What "
          f"the abstentions buy is that the remaining answers can be acted on "
          f"without re-reading, and that the abstentions arrive grouped: "
          f"`docs/sample_worklist.md` is what a person is actually handed.", ""]
    # Where the gap actually sits. `docs/EVAL_PROTOCOL.md` prediction 4 required
    # this split before the gap was reported, and the coverage row is the place a
    # reader is most likely to read the gap as accuracy.
    gap = res.get("k0_gap_by_stratum")
    if gap:
        d = gap["definite"]
        b2r = d["B2"]["wrong"] / d["B2"]["answered"] if d["B2"]["answered"] else 0
        tsr = d["TS"]["wrong"] / d["TS"]["answered"] if d["TS"]["answered"] else 0
        i = gap["indeterminate"]
        L += [f"**And the gap is abstention rather than accuracy.** Split those cells "
              f"by whether an answer exists. On the {d['cells']} where gold is MEETS or "
              f"FAILS, B2 is wrong on {b2r:.1%} of what it answered and TrialSieve on "
              f"{tsr:.1%}, so the baseline is the more accurate arm there. The whole "
              f"difference sits in the {i['cells']} cells where the record does not "
              f"say, where B2 commits on {i['B2']['answered']} and TrialSieve on "
              f"{i['TS']['answered']}. `results/RESULTS.md` carries the split under "
              f"*The k = 0 gap*, which "
              f"`docs/EVAL_PROTOCOL.md` required before the gap could be reported.", ""]

    L += ["An arm can win the reduction row by ruling out everybody. B0 does "
          "exactly that, reduces the panel by 100%, and wrongly excludes "
          f"{paired['panel_scores']['B0']['false_exclusions']} of {n_screens} "
          "screens. That is why the registered outcome is VOID at any non-zero "
          "false-exclusion count rather than a reduction figure with a caveat.", ""]
    # This paragraph used to say no interval was printed here, on purpose. It
    # then had to say something else, because the row a reader quotes most often
    # is ten false exclusions against two and the interval on that difference
    # includes zero. Withholding it and pointing at another file is a choice that
    # only ever runs one way.
    crossing = [c for c in paired.get("paired_bootstrap", [])
                if c["arms"] == "TS - B2" and c["crosses_zero"]]
    L += ["**Where the uncertainty is.** The brief's suggested format has four "
          "columns and none of them is a confidence interval, so this table keeps "
          "its shape and carries the interval inside the row it qualifies rather "
          "than in a fifth column. Every difference here is bootstrapped in "
          "`results/RESULTS.md`, resampling unique criteria and patients, and "
          "each one is printed against the rate at which two independent "
          "labellers contradict each other.", ""]
    if crossing:
        names = ", ".join(f"`{c['metric']}`" for c in crossing)
        L += [f"**The one that does not separate from chance.** Of the three "
              f"`TS - B2` differences, {names} has a 95% interval that includes "
              f"zero. That is the false-exclusion comparison, which is the "
              f"headline figure of this project, and on 400 cells it is a real "
              f"reduction that this evaluation is not powered to distinguish from "
              f"a lucky draw. The silent error rate and the coverage differences "
              f"do exclude zero. Nothing here is reported as significant that is "
              f"not.", ""]
    L += ["**And the floor moved.** `results/RESULTS.md` prints every difference "
          "against two label noise floors: the poststratified one that amendment "
          "A7 introduced after the scored run existed, and the unweighted sample "
          "rate it replaced. Exactly one row changes verdict between them, and it "
          "is the false-exclusion row, which A7 moved from borderline to above. "
          "The comparison that falls below either floor is TrialSieve against B1, "
          "the demographics-only floor, and `results/RESULTS.md` marks those rows "
          "**below, uninterpretable** rather than reporting them as a result.", ""]

    L += ["## Where this differs from the suggested format", ""]
    L += ["- The brief's single **primary outcome** row is split into the "
          "registered outcome and the harm behind it, because a reduction figure "
          "beside a non-zero false-exclusion count is not one number.",
          "- **Human time per task** is not a timing. Nobody was timed, and a "
          "made-up minutes-per-chart figure would be the least defensible number "
          "in this repository. What is counted is judgements left to a person and "
          "how many distinct questions they collapse into.",
          "- **Cost per task** is reported per panel rather than per task, "
          "because the unit that matters is the whole screening pass and the two "
          "arms scale differently in it: one compiles once and then does "
          "arithmetic, the other pays per cell.", ""]
    return "\n".join(L).rstrip() + "\n"


def _cost_rows() -> str:
    """The cost row, lifted from the same table `docs/COST.md` publishes."""
    path = ROOT / "docs" / "COST.md"
    if not path.exists():
        return ""
    for line in path.read_text(encoding="utf-8").splitlines():
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) == 3 and cells[0].isdigit() and int(cells[0]) > 100:
            return (f"| **Cost per panel** of {int(cells[0])} patients, at "
                    f"an illustrative hosted rate | {cells[2]} | **{cells[1]}** | the "
                    f"crossover is in `docs/COST.md` |")
    return ""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="fail if the committed file is not what this run would write")
    a = ap.parse_args()
    text = build()
    if a.check:
        have = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if have != text:
            print(f"{OUT.relative_to(ROOT)} is stale; run `python scripts/scorecard.py`",
                  file=sys.stderr)
            return 4
        print(f"PASS: {OUT.relative_to(ROOT)} matches the current run.")
        return 0
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
