"""The one table a judge asked for, generated from the scored run.

The challenge brief suggests a three-row comparison: primary outcome, human time
per task, cost per task, with a column for the simple baseline and one for the
agent solution. It also says to propose a different rubric where that one fits
badly. Both apply here, so this writes the suggested shape and says plainly
where it was adapted and why.

Two adaptations, both stated in the output rather than only here:

1. A single "primary outcome" row would hide the trade this project is about.
   `docs/EVAL_PROTOCOL.md` registers the outcome as panel reduction at zero false
   exclusions and VOID otherwise, so the reduction is reported next to the count
   that voids it, and the harm gets its own row.
2. Human time is not a stopwatch reading. Nobody was timed. What is measured is
   the number of judgements a person is left holding, which is the quantity a
   coordinator's hours are actually spent on, and the number of distinct
   questions those judgements collapse into.

Every figure comes from `results/results.json` and `docs/sample_worklist.json`.
Nothing here is typed in by hand, and `--check` fails if the file on disk has
drifted from what the current run would produce.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "SCORECARD.md"

#: The paired group. B2 is the only baseline that costs a model call per cell, so
#: it was recorded over a seeded sample rather than the whole panel. Every arm in
#: this group is scored on those same 400 cells, which is what makes the
#: comparison fair rather than merely available.
PAIRED = "b2_10p"
FULL = "k0_seed7"


def _pct(x: float) -> str:
    return f"{x * 100:.2f}%"


def _ratio(worse: float, better: float) -> str:
    """The ratio between two silent error rates.

    Never print this on its own. `evaluation/score.py` opens by saying the unit
    of result is the ordered pair (coverage, SER), because an arm that abstains
    everywhere has a silent error rate of exactly zero and is worthless. Every
    caller here prints the two coverages in the same row.
    """
    if better <= 0:
        return "no error to divide by"
    return f"{worse / better:.0f}x lower"


def build() -> str:
    res = json.loads((ROOT / "results" / "results.json").read_text(encoding="utf-8"))
    wl_path = ROOT / "docs" / "sample_worklist.json"
    wl = json.loads(wl_path.read_text(encoding="utf-8")) if wl_path.exists() else {}

    paired = res["groups"][PAIRED]
    full = res["groups"][FULL]
    ts, b2 = paired["cell_scores"]["TS"], paired["cell_scores"]["B2"]
    tsp, b2p = paired["panel_scores"]["TS"], paired["panel_scores"]["B2"]
    n_cells = ts["n_cells"]
    n_screens = paired["n_screens"]

    L: list[str] = []
    L += ["# The comparison table, in the shape the brief asks for", ""]
    L += [f"Generated by `python scripts/scorecard.py`. Every number is read from "
          f"`results/results.json`, and the human-time row also from "
          f"`docs/sample_worklist.json`. `python run.py reproduce` regenerates "
          f"both offline from recorded model calls.", ""]
    L += [f"The rows below are scored on **the same {n_cells} cells**: "
          f"{n_screens} screens, meaning ten patients each read against three "
          f"trials, against the criteria that compiled, judged by "
          f"both arms. B2 is the only baseline that spends a model call per cell, "
          f"so it was recorded over a seeded sample rather than the full "
          f"{full['cell_scores']['TS']['n_cells']:,}-cell panel, and every arm it "
          f"is compared against is re-scored on that sample rather than quoted "
          f"from the larger run.", ""]

    L += ["## The simple baseline", ""]
    L += ["**B2: one model call per cell.** The criterion text and a flattened "
          "patient record go to the model, which answers MEETS, FAILS or "
          "INDETERMINATE. It is the brief's first suggested baseline, one direct "
          "prompt with basic instructions, and it is the version of this task "
          "most people would build first. Two weaker arms are also carried "
          "through the report: B0 answers FAILS whenever it sees no evidence, and "
          "B1 answers only what a regular expression can settle.", ""]

    L += ["## The table", ""]
    L += ["| metric | simple baseline (B2) | TrialSieve | change |",
          "|---|---|---|---|"]
    L.append(f"| **Primary outcome** as registered: panel reduction at zero false "
             f"exclusions | **VOID** ({b2p['false_exclusions']} false exclusions, "
             f"reduction {_pct(b2p['reduction'])}) | **VOID** "
             f"({tsp['false_exclusions']} false exclusions, reduction "
             f"{_pct(tsp['reduction'])}) | both void; the harm behind the void "
             f"falls from {b2p['false_exclusions']} to {tsp['false_exclusions']} |")
    L.append(f"| Screens wrongly ruled out, of {n_screens} | "
             f"{b2p['false_exclusions']} | **{tsp['false_exclusions']}** | "
             f"{b2p['false_exclusions'] - tsp['false_exclusions']} fewer |")
    # The change column used to read a bare "44x lower". `evaluation/score.py`
    # says in its opening docstring that a comparison against an arm at higher
    # coverage is not admissible, and this is exactly that comparison: TS at
    # 21.75% against B2 at 68%. Printing the ratio alone in the headline table,
    # under a module that calls it inadmissible, is the submission arguing
    # against itself. The row carries both coverages now and sends the reader to
    # the paired interval.
    L.append(f"| Silent error rate per cell, each at the coverage beside it | "
             f"{_pct(b2['ser'])} at {_pct(b2['coverage'])} coverage | "
             f"**{_pct(ts['ser'])}** at {_pct(ts['coverage'])} coverage | "
             f"{_ratio(b2['ser'], ts['ser'])}, at a third of the coverage |")
    L.append(f"| Cells answered with a definite verdict | {_pct(b2['coverage'])} | "
             f"{_pct(ts['coverage'])} | lower on purpose, see below |")
    L.append(f"| Wrong MEETS, the verdict that enrols someone who should not be | "
             f"{b2['n_false_meets']} | **{ts['n_false_meets']}** | "
             f"{b2['n_false_meets'] - ts['n_false_meets']} fewer |")

    if wl:
        sets = wl.get("question_sets") or []
        n_q = len(wl.get("distinct_open_criteria") or [])
        # This row is the one trial the worklist was rendered for, not the 400
        # cells above, and it says so. Quietly changing denominator mid-table is
        # how a comparison stops being one.
        L.append(f"| **Human time per task**, as judgements a person is left "
                 f"holding *(one trial, {wl['n_screens']} patients, not the "
                 f"sample above, and against the {len(wl['criteria_used'])} "
                 f"criteria this operating point applies rather than the trial's "
                 f"full set)* | {wl['n_cells']:,} cell judgements, the manual "
                 f"process today | {wl['n_review']:,} screens carrying **{n_q} "
                 f"distinct open questions** | {len(sets)} thing(s) to go and "
                 f"find instead of {wl['n_cells']:,} separate readings. Each "
                 f"still returns a value per patient; what collapses is the "
                 f"search, not the answers |")

    costs = _cost_rows()
    if costs:
        L.append(costs)
    L.append("")

    L += ["**On the ratio in that row.** It is the arithmetic and it is not the "
          "result. `evaluation/score.py` states that a comparison against an arm "
          "at higher coverage is not admissible, and this is that comparison: "
          f"TrialSieve answers {_pct(ts['coverage'])} of cells and B2 answers "
          f"{_pct(b2['coverage'])}. The row that does settle it is the paired "
          "bootstrap in `results/RESULTS.md`, where `TS - B2` on `ser` is "
          "reported with an interval and against the label noise floor. The "
          "ratio is here because the brief's table has a change column, not "
          "because it is the finding.", ""]
    L += ["## Reading the coverage row honestly", ""]
    L += [f"TrialSieve answers fewer cells than B2 and that is the design, not a "
          f"shortfall. B2 commits to {_pct(b2['coverage'])} of cells and is wrong "
          f"on {_pct(b2['ser'])} of all cells; TrialSieve commits to "
          f"{_pct(ts['coverage'])} and is wrong on {_pct(ts['ser'])}. A "
          f"coordinator cannot use an answer that is wrong two times in five, "
          f"because checking which two costs the same as reading the chart. What "
          f"the abstentions buy is that the remaining answers can be acted on "
          f"without re-reading, and that the abstentions arrive grouped: "
          f"`docs/sample_worklist.md` is what a person is actually handed.", ""]
    L += ["An arm can win the reduction row by ruling out everybody. B0 does "
          "exactly that, reduces the panel by 100%, and wrongly excludes "
          f"{paired['panel_scores']['B0']['false_exclusions']} of {n_screens} "
          "screens. That is why the registered outcome is VOID at any non-zero "
          "false-exclusion count rather than a reduction figure with a caveat.", ""]
    L += ["**No interval is printed in the table above, on purpose.** The brief's "
          "suggested format has four columns and none of them is a confidence "
          "interval, and inventing a fifth would make this table something other "
          "than the one that was asked for. Every row here has its interval and "
          "its comparison against the label noise floor in `results/RESULTS.md`, "
          "which is where a difference should be judged interpretable or not. The "
          "rows above compare B2 against TrialSieve, and every `TS - B2` row in that "
          "file is marked `above` the floor rather than below it. The comparison "
          "that does fall below is "
          "TrialSieve against B1, the regular-expression arm, and `results/RESULTS.md` "
          "marks those rows **below, uninterpretable** rather than reporting them as "
          "a win.", ""]

    L += ["## Where this differs from the suggested format", ""]
    L += ["- The brief's single **primary outcome** row is split into the "
          "registered outcome and the harm behind it, because a reduction figure "
          "beside a non-zero false-exclusion count is not one number.",
          "- **Human time per task** is not a timing. Nobody was timed, and a "
          "made-up minutes-per-chart figure would be the least defensible number "
          "in this repository. What is counted is judgements left to a person and "
          "how many distinct questions they collapse into.",
          "- **Cost per task** is reported per panel rather than per task, "
          "because the unit that matters is the whole screening pass and the two "
          "arms scale differently in it: one compiles once and then does "
          "arithmetic, the other pays per cell.", ""]
    return "\n".join(L).rstrip() + "\n"


def _cost_rows() -> str:
    """The cost row, lifted from the same table `docs/COST.md` publishes."""
    path = ROOT / "docs" / "COST.md"
    if not path.exists():
        return ""
    for line in path.read_text(encoding="utf-8").splitlines():
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) == 3 and cells[0].isdigit() and int(cells[0]) > 100:
            return (f"| **Cost per panel** of {int(cells[0])} patients, at "
                    f"published rates | {cells[2]} | **{cells[1]}** | the "
                    f"crossover is in `docs/COST.md` |")
    return ""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="fail if the committed file is not what this run would write")
    a = ap.parse_args()
    text = build()
    if a.check:
        have = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if have != text:
            print(f"{OUT.relative_to(ROOT)} is stale; run `python scripts/scorecard.py`",
                  file=sys.stderr)
            return 4
        print(f"PASS: {OUT.relative_to(ROOT)} matches the current run.")
        return 0
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
